로그인 기능 구현
f-lab-edu/double-shop pull request #18
Opened 2021-10-03 21:01 UTC by wilco82

# 주요 작업

- 회원 로그인/로그아웃
  - 로그인 인터셉터 및 Argument Resolver 추가: `LogInCheckInterceptor`, `LogInMemberArgumentResolver` 정의
  - 웹 설정 파일 추가: `WebConfig` 정의

- 마이 페이지
  - 마이 페이지 핸들러 `getMemberInfo` 정의

- 이메일 인증
  - `JavaMailSender`와 `SimpleMailMessage`를 이용하여 이메일 인증 기능 구현
  - 이메일 내용은 템플릿 클래스로 분리하여 관리

- 비밀번호 찾기

1. 찾고자 하는 계정의 아이디를 입력
2. 등록된 이메일 또는 휴대폰으로 인증번호 전송
3. 인증확인 완료 시 사용자가 비밀번호 변경

   - 입력받은 아이디가 존재한다면 휴대폰/이메일 인증 중 한 가지를 선택하도록 구현
     * 휴대폰 인증: `sendSms`, `verifySms`
     * 이메일 인증: `sendEmail`, `verifyEmail`

- 리뷰 반영
  - `SHA256EncryptionUtil` 암호화 과정에서 불필요한 변수 삭제
  - 중복검사 쿼리에서 기존의 COUNT를 가져오는 쿼리에서 최상위 한 개만 가져오는 쿼리로 수정
  - 회원 Repository를 정의하여 기존의 Mapper로 DI 받는 코드를 캡슐화하여 정의

2021-10-05 09:42 UTC, wanniDev requested changes
- 인증 관련 로직은 spring security를 적용하고 나서, 진행하는 게 좋을 것 같습니다.
- 기존에 진행 하신 코드를 검증할 수 있는 테스트 코드가 있었으면 합니다.

2021-10-05 09:42 UTC, wanniDev commented on src/main/java/com/project/doubleshop/domain/member/service/LogInService.java
> +    private final HttpSession session;
HttpSession을 전역 변수로 두는게 맞을까요? 그리고 요청으로부터 처리해야할 session을 service 타입의 로직으로 관리하는게 맞는지 조금 의문이 듭니다.

2021-10-05 09:42 UTC, wanniDev commented on src/main/java/com/project/doubleshop/domain/member/service/LogInService.java
> +        session.setAttribute("userId", userId);
session name은 constant화 해서 사용하시는게 좋을 것 같고, `userId` 만 넣어서 또 따로 DB 네트워크를 타는 건 효율이 좋아보이진 않습니다.

2021-10-05 09:42 UTC, wanniDev commented on src/main/java/com/project/doubleshop/domain/member/entity/Member.java
> +
DTO를 entity로 변환하는 로직이 필요할까요?

2021-10-06 03:13 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/domain/member/service/EmailVerificationService.java
> +    public static final String SENDER_ADDRESS = "carpedm082@gmail.com";
요런 데이터는 app property로 빼는걸 고려해보시기 바랍니다. (설정파일)

2021-10-06 03:16 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/domain/utils/verification/email/EmailContentTemplate.java
> +    }
@Setter를 쓰지않고 따로 넣은 이유가 있을까요?

2021-10-06 03:17 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/web/config/MailConfig.java
> +        mailSender.setPort(25);
여기에 쓰이는 host, protocol, port도 app property로 빼는걸 고려해보시면 좋겠습니다.

2021-11-08 12:13 UTC, wilco82 commented
기존 SMS 인증 관련 코드에서 설정 데이터를 소스에 포함하여 커밋/푸시하는 과정에서 GitHub의 코드 스캐닝으로 인해 해당 데이터가 폐기되었습니다. 일단 인증 클래스를 추상화하는 방법도 생각했지만, 해당 클래스를 굳이 추상화하여 구현할 필요가 없다고 판단했습니다. 그래서 폐기된 데이터를 Twilio에서 재발급 받고, 스캐닝을 피하면서 보다 안전한 데이터 관리를 위해 **Azure Key Vault**를 외부 저장소로 채택하여, 데이터를 직접 코드에 선언하는 기존의 방식에서 Key Vault를 생성하고 계정 시드, 인증 토큰, 발신자 번호를 **secret 데이터로 저장하여 주입받는 방식**으로 수정하고자 합니다. 


> **기존 코드** `public static final String ACCOUNT_SID = "AC86c9a7f3df4e9b910b4fa64ff13db261";`

> **새로운 코드** `@Value("${account-sid}") private String ACCOUNT_SID;`

관련해서 의견 남겨주시면 감사하겠습니다.

2021-11-08 12:53 UTC, wanniDev commented
기억하고 계실진 모르겠지만, sms, email 인증 코드관련 추상화를 하자는 내용은 저번 멘토링 세션 때, 의견 교환을 하며, 정한 내용이었습니다.

 이유는 외부 API에 대해 사전 검토 및 의견 교환을 하지 않고 진행 하셨었는데, 예기치 못한 문제로 Twilio를 폐기하고 다른 API로 교체해야할 때, 작업을 좀더 유연하게 하기 위함이기도 하고, 또 하나는, 테스트를 할 때는 꼭 외부 API의 응답을 받을 필요가 없기 때문에, 추상화한 객체로 요청 자체에 문제가 없는지의 여부만 확인할 수 있게 하기 위함입니다.(이 부분에 대한 자세한 설명은 토비의 스프링을 참고하면 좋을 것 같습니다.)
 그런데, `해당 클래스를 굳이 추상화하여 구현할 필요가 없다고 판단했습니다.` 하고 넘기셨는데, 사전에 합의했던 내용을 넘긴 것 치고는 근거가 너무 불분명 합니다...

 그리고 종전에 DM으로도 이야기 했지만, 지금까지 구현하셨던 회원가입, 사용자 인증 관련 코드를 우선 본인에게 익숙한 방식으로 구현을 해오셨다고 했는데, 그래서 그런지, Security를 적용할 경우, 기존 코드와 안맞는 경우가 많았습니다. 따라서, 기존 코드가 아예 사라질 수도 있고, 인증 방식에도 변화가 있을 수 있으니 미리 양해를 구합니다.

PS. 그리고 제금 application.yml에 conflicts가 발생했네요. 다른 사용자가 같은 파일을 쓰고 있어서 그런 것 같네요. 롤백하시고, 다른 yml 파일을 사용하시는 게 좋을 것 같습니다.

2021-11-08 17:26 UTC, wanniDev commented
회의 후에 기록을 하지 않은 부분이 있어, 분명히 커뮤니케이션 관련해서, 혼동이 있을 순 있지만, `프로젝트 사전 회의 중에 제가 몇 개의 API를 언급` 했다는 점은 조금 받아들이기 힘드네요;; 제가 기억하기로는 회원가입 과정에서 이메일, SMS 인증 기능을 넣어보는 게 어떻겠냐고 제안하신걸로 알고있었지, 그 과정에서 구체적으로 사용할 라이브러리가 어떤건지에대해선 아무 말씀이 없으셨던걸로 알고 있습니다. `Twilio` 적용은 언급이 없으셨다가 이미 다 적용하신 다음에 말씀하신게 맞습니다. 사실, 강우님 본인이 사전 검토를 하고, 라이브러리의 안정성을 증명하는 문서를 제시하셨거나 했다면, 모르겠는데, 그 과정을 생략하시고 계속 진행하시기에, 리뷰에선 언급이 없다가, 세션 중에 이야기를 꺼낼 수 밖에 없었습니다 그리고, 구현하고나서 시간이 지나서야 세션 중에 이야기를 한 이유는 제가 모르고 넘어간 부분이 있었는지 확인할 시간이 필요했었기 때문입니다. (그리고, 만약 제가 틀렸다면, 멘토님께서 제재를 하실 수도 있겠다는 생각도 들었구요).

 그리고 `당장 통제가 되지 않는다면 추상화를 해주시고 그게 아니라면 구현까지 하는 방향으로 판단`을 직접 말씀했다고 했는데, 저는 여기서 작업 방향을 **공유** 했으면 좋겠다라고도 언급 했었습니다. 추상황 관련 이야기를 이제서야 리뷰를 해드린 이유는 강우님께서 제가 부탁드렸던 부분(작업 방향 공유)을 한달 가까이 생략하고 계시다가, 갑자기 달라진 작업 방향을 통보하시면서, pr이 conflits인 상태를 방치하고 계신데, 솔직히 말씀드리자면, 당황스러워야할 사람은 저인 것 같네요.

 그리고 덧붙여서, 현재, Security 부분은 원래 강우님이 하시기로 했다가, 제가 맡게 되었는데, 지금 인증 방식은 그대로 사용하기에는, Security와 api 인증 컨셉과 조금 많이 안맞습니다. 따라서, 현재 PR은 닫고, 인증, 회원가입 로직은 프레임워크에 맞게 재설계해서 적용하는게 나을 것 같습니다. (일찍 발견못한 제 잘못이 크니, 이 부분은 제가 진행하도록 하죠.)

 그리고, Twilio 라이브러리는 저번 세션때도 이야기 했지만, 우선 보류하는게 나을 것 같습니다. spring 이나 java 진영에서 공식화가 진행되지 않은 사설 기업의 **유료** 라이브러리인데, 그냥 적용하는 것은 아무리 생각해도 위험한 것 같습니다.

2021-11-09 13:35 UTC, wanniDev commented on src/test/java/com/project/doubleshop/domain/member/service/LogInServiceTest.java
> +
`@ActiveProfiles("test")` 이걸 써주셔야, 테스트용 db가 작동합니다.

2021-11-09 14:35 UTC, wanniDev requested changes

2021-11-09 14:35 UTC, wanniDev commented on src/test/java/com/project/doubleshop/domain/member/service/LogInServiceTest.java
> +
테스트 환경의 설정을 적용하셔야 합니다. 이번에 작성하신 테스트 클래스에 `@ActiveProfiles("test")`를 기입해주세요.

2021-11-10 05:01 UTC, wanniDev commented
@wilco82 안녕하세요. 어제 DM으로 같이 conflicts 관련해서, 해결하고자 서로 고민을 많이 했었는데.. 우선 제 pr에서 나타났던 문제는 강우님의 pr에서 나타난 문제와는 다른 문제였습니다. `Nested Servlet Error`로, 스프링의 argument resolver와 제가 커스터마이징한 pageable argument resolver가 충돌하여, 핸들러 디스패치가 안됨으로서 테스트가 아예 작동하지 않은게 원인이었습니다. 현재는 해결하였습니다.

 다만, 이번에 생긴 conflicts는 제가 건들였던 파일(공백 포함)을 강우님께서도 건들이셔서 일어난 충돌인걸로 판단됩니다. 물론 이 부분은 제가 미리 알려드리지 않아서 생긴 문제라, 저 역시 책임의식을 갖고 있습니다.

 조금 귀찮으실지는 모르겠지만, conflicts를 명확하게 해결하기 힘든 상황인점을 감안하여, 이번 pr은 닫으시고 현재 코드를 백업하셔서 새로 pr을 열어서 다시 작성하시는 게 어떤지 여쭙고 싶습니다. 물론 더 좋은 방법이 있다면 얼마든지 의견 부탁드리겠습니다.

2021-11-11 13:24 UTC, closed without merging