인증 서비스 추상화 적용
f-lab-edu/double-shop pull request #26
Opened 2021-11-26 06:43 UTC by wilco82

# 작업내역
- SMS 인증 서비스 추상화
      - 특정 인증 API만을 사용하는 기존 코드를 구현 클래스로 재정의

- 이메일 인증 서비스 추상화
      - Gmail SMTP 서버를 사용하는 기존 코드를 구현 클래스로 재정의

- 인증 서비스에 템플릿 클래스 적용

2021-11-26 15:06 UTC, wanniDev requested changes
안녕하세요. 로직의 오류 발생여부만 놓고보면, 문제는 없을 것 같지만, [위키](https://github.com/f-lab-edu/double-shop/wiki/02.-%EC%9C%A0%EC%A6%88%EC%BC%80%EC%9D%B4%EC%8A%A4)에 기재한 유즈케이스를 참고해보았을 때, 저희가 이메일과, sms를 통해 세션유지를 하려는 것이 아니라, 각각 중복확인, 본인인증을 하는 데 session을 사용하는 것은 다소 어색해 보입니다. 그리고, 세션관리 로직이 구체화되지 않은 상황에서는 HttpSession를 바로 사용하는 것보다는 먼저 커뮤니케이션을 통해 서로 체크하는 과정이 필요해 보입니다.

2021-11-28 08:29 UTC, wanniDev commented on src/main/java/com/project/doubleshop/web/member/controller/MemberController.java
>      }
아, 그리고 사전에 통보했듯이, 현재 `MemberController`는 삭제되고, 앞으로 사용자 api는 `MemberRestController`로 옮겨질 예정입니다. 현재 코드를 그대로 두시면 conflicts가 날 것 같습니다. 삭제해주세요.

2021-11-28 12:18 UTC, wilco82 commented on src/main/java/com/project/doubleshop/domain/member/service/EmailVerificationService.java
> +    public void sendEmail(String email, HttpSession session);
기존 코드를 보시면 아시겠지만, 해당 이메일로 전송된 인증번호의 입력 제한 시간을 위해서 설정했던 세션이었습니다. 제한 시간이 지나면 해당 세션이 만료되어서 사라지게 되는 의도로 작성했었습니다. 클라이언트의 세션 상태를 유지하려는 것이 아닌 단순히 입력받은 인증 번호의 일치 여부만 체크하기 위한 일회성 세션이고, 말씀해 주신 중복 확인과는 전혀 관련이 없습니다.

2021-11-28 12:18 UTC, wilco82 commented on src/main/java/com/project/doubleshop/domain/member/service/TwilioSmsVerificationService.java
> +
네, 이전 세션에서도 말씀드렸지만 Twilio 인증 관련 서비스 클래스는 실제 서비스 로직에 사용하려는 것이 아니라, 이후에 SMS 인증 방식을 사용할 경우 테스트 과정에서 활용하기 위해서 일단 남겨두었던 파일입니다. 언급해 주신 것처럼 일단 이메일 인증에 집중해서 구현할 생각입니다.

2021-11-28 12:19 UTC, wilco82 commented
안녕하세요. 사실 이 PR에 있는 코드들은 Spring Security 적용을 끝내시고 저희끼리 이후 회의를 진행하기 전에 이미 작성했던 코드였습니다. 그래서 저희가 합의했던 부분이 반영되지 않고 제가 이전에 회원 관련 구현을 맡았을 당시에 사용되었던 로직들이 그대로 남아있었네요. 다시 확실하게 검토해 보고 PR을 했어야 했는데 제가 너무 성급했던 것 같습니다. 커뮤니케이션 과정이 선행되어야 한다는 점은 물론 저도 동의합니다.

말씀해 주신 것처럼 인증 관련 서비스는 형중님께서 Security 관련 설정을 직접 구현해 주신 만큼, 제가 단독으로 고쳐나가는 것보다 서로 다시 검토하는 과정을 먼저 거쳐야 할 것 같습니다. 말씀해 주신 컨트롤러 클래스는 일단 삭제하겠습니다.

2021-11-28 13:16 UTC, wanniDev commented on src/main/java/com/project/doubleshop/domain/member/service/EmailVerificationService.java
> +    public void sendEmail(String email, HttpSession session);
그러셨군요. 이메일 인증에 대한 부분은 제가 조금 오해했던 부분이 있었네요. 다만, 저희는 Token Based(쿠키에 세션ID에 저장하는 것이 아니라, 헤더에 토큰 키를 포함하여, 세션 서버에 조회하는 방식) Authentication을 진행할 예정입니다. 다만, 일반적이지 않은 인증 방식이라는 점에서, 간단하게 언급하고 넘어갈 문제는 아닌 듯 하네요. 이 부분은 제가 문서화를 해서 wiki에 배포할테니, 우선은 보류해주세요.

2021-12-06 06:00 UTC, f-lab-jason commented
`EmailVerificationService`와 `SmsVerificationService`는 하나로 통합해도 될 것 같습니다.
이 verification service를 위해 필요한게
1. 난수 생성
2. 컨텐츠 생성
3. 전송
4. 검증
네 가지 일 것 같은데 Email과 Sms은 대상만 다르지 행위 자체는 같을 것으로 보이네요.

2022-01-20 12:19 UTC, closed without merging