회원가입 구현
f-lab-edu/double-shop pull request #8
Opened 2021-09-18 07:17 UTC by wilco82

- 회원가입 구현
- 비밀번호 암호화 구현
- 아이디 & 이메일 중복검사
- 유효성 검사
- Mapper 정의

2021-09-18 12:31 UTC, wanniDev commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +    private MemberInfoMapper memberInfoMapper;
안녕하세요. 혹시 Service에 Mapper를 직접 사용하신 이유를 알려주실 수 있을까요?

2021-09-18 13:45 UTC, wanniDev reviewed
안녕하세요. 처음으로 다른 사람의 코드에 리뷰를 달아봅니다. 🙂
저와 코드를 진행하는 스타일이 다르지만, 나름 많은 걸 배웠습니다. 특히, 정규식은 어려워서 잘 사용안하려는 경향이 있었는데, 이 부분을 적극 활용하는 부분은 정말 인상 깊었습니다. 다만 패키지 구조에 대해서는 사전에 미리 토의를 하고 정한 틀이 있었는데, 그 부분을 반영하지 않으신 부분은 조금 당황스러웠습니다. ;; 세부 리뷰내용에도 이야기 했지만, 간단히 요약하자면,
`com.project.doubleshop.domain.도메인이름.*`
`com.project.doubleshop.web.도메인이름.*`
 이런 식으로 진행하고자한게 기존에 구글밋으로 토의한 프로젝트 패키지의 큰 틀에 대한 내용 이었습니다. 아 그리고, f-lab에서 적극적으로 권장하는 사항 중 하나가 멘티끼리도 활발하게 리뷰를 하자는 항목이 있는 걸로 알고 있습니다. 리뷰어에서 멘토님만 등록하셨던 것 같은데, 저도 리뷰어로서 참여할 수 있게 해주셨으면 좋겠고, 제가 올린 pull request에도 적극적으로 리뷰를 해주시기 바랍니다. 감사합니다.

2021-09-18 13:45 UTC, wanniDev commented on src/main/java/com/project/doubleshop/service/MemberService.java
> +package com.project.doubleshop.service;
이 부분은 데이터 액세스 로직으로 얻은 데이터로 비즈니스 로직을 진행하는 부분이니, 저희가 사전에 합의한 대로라면,
`com.project.doubleshop.domain.member.service`에 옮기는 것이 좋을 것 같습니다.

2021-09-18 13:45 UTC, wanniDev commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +package com.project.doubleshop.service.impl;
같은 맥락입니다. `com.project.doubleshop.domain.member.service` 로 옮기는 것이 좋을 것 같습니다.

2021-09-18 13:45 UTC, wanniDev commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +package com.project.doubleshop.dto;
이 부분도 역시 `com.project.doubleshop.web.member` 로 옮겨 주세요. 필요하면 dto 패키지를 별도로 생성하셔서 넣어도 무방할 듯 합니다.

2021-09-18 13:45 UTC, wanniDev commented on src/main/java/com/project/doubleshop/model/enums/Type.java
> +package com.project.doubleshop.model.enums;
여기도 부탁 드리겠습니다. 🙂

2021-09-18 13:45 UTC, wanniDev commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +    @Pattern(regexp = "^(?=.*[a-zA-Z0-9]).{6,12}$", message = "아이디는 영문/숫자 조합 6~12자리")
DTO는 단순히 data를 transfer하는 객체로, 별도의 로직이 들어가지 않고, 데이터를 담고 전송하기만 하는 책임을 가진 객체인 걸로 알고 있습니다. 그러한 객체에 validation 애노테이션으로 검증 로직을 넣어도 될까요? 이 부분에 대해서 강우님의 생각을 알고 싶습니다.

2021-09-19 01:37 UTC, wilco82 commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +    private MemberInfoMapper memberInfoMapper;
제 의도는 서비스 계층에서 Mapper 객체를 의존성 주입으로 가져와서 바로 사용하도록 하는 것이 목적이었습니다.
MyBatis를 공부하면서 구글링으로 봤던 여러 샘플 코드에서도 이런 방식으로 구현을 해서 참고해봤습니다.
이 부분은 제가 아직 웹 개발에 대한 지식이 부족해서 잘 모르는 부분이 있을 수 있겠는데요, 혹시 잘못된 부분이 있거나 더 좋은 방향을 제시해주시면 반영해보겠습니다.

2021-09-19 01:37 UTC, wilco82 commented on src/main/java/com/project/doubleshop/controller/MemberController.java
> +package com.project.doubleshop.controller;
네, 그 부분은 제 실수가 있었네요. 반영하겠습니다.

2021-09-19 01:38 UTC, wilco82 commented on src/main/java/com/project/doubleshop/mapper/MemberInfoMapper.java
> +package com.project.doubleshop.mapper;
반영하겠습니다.

2021-09-19 01:38 UTC, wilco82 commented on src/main/java/com/project/doubleshop/model/enums/Authority.java
> +package com.project.doubleshop.model.enums;
반영하겠습니다.

2021-09-19 01:38 UTC, wilco82 commented on src/main/java/com/project/doubleshop/model/enums/Grade.java
> +package com.project.doubleshop.model.enums;
반영하겠습니다.

2021-09-19 01:38 UTC, wilco82 commented on src/main/java/com/project/doubleshop/model/enums/Status.java
> +package com.project.doubleshop.model.enums;
반영하겠습니다.

2021-09-19 01:39 UTC, wilco82 commented on src/main/java/com/project/doubleshop/service/MemberService.java
> +package com.project.doubleshop.service;
반영하겠습니다.

2021-09-19 01:39 UTC, wilco82 commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +package com.project.doubleshop.service.impl;
반영하겠습니다.

2021-09-19 01:39 UTC, wilco82 commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +package com.project.doubleshop.dto;
반영하겠습니다.

2021-09-19 01:39 UTC, wilco82 commented on src/main/java/com/project/doubleshop/model/enums/Type.java
> +package com.project.doubleshop.model.enums;
반영하겠습니다.

2021-09-19 01:39 UTC, wilco82 commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +    @Pattern(regexp = "^(?=.*[a-zA-Z0-9]).{6,12}$", message = "아이디는 영문/숫자 조합 6~12자리")
일단 유효성 검사는 프런트 단에서 할 수도 있지만 프런트 쪽에서만 검사를 하는 것은 보안상의 문제가 있기 때문에, 백엔드에서도 검사를 해주는 것이 좋다고 들었습니다.

말씀해주신 것처럼 DTO가 데이터 전달자의 책임을 갖는다는 점은 동의합니다. 다만 저는 클라이언트가 요청하는 데이터가 DTO 객체로 캡슐화되어 서버로 전달되는 과정을 생각해 보았을 때, 컨트롤러에서 request로 오는 DTO에서 검증을 하는 것이 더 자연스러울 것 같다라는 생각이 들었습니다. 그렇게 되면 컨트롤러의 해당 핸들러 메서드에서도 Valid 애노테이션과 함께 유효성 검사를 할 수 있게 됩니다.

그리고 애노테이션을 사용한 이유는, 유효성 검사를 다른 계층에서 구현할 수도 있겠지만 그렇게 되면 코드가 다소 지저분해질 것 같았습니다. 거의 동일한 내용의 검증 로직이 각 계층별로 구현된다면 낭비가 심한 작업이 될 수 있고, 검증 로직 간에 불일치로 오류가 발생할 수도 있겠다고 생각했습니다.
그래서 애노테이션을 사용해서 선언적으로 도메인 객체를 검증하고 에러 메시지도 message 속성으로 한번에 담을 수 있는 좀 더 편하고 직관적인 방법을 사용했습니다. @Email 애노테이션을 보시면 아시겠지만, 이메일 형식을 검사하기 위해서 정규표현식 자체를 사용하지 않아도 됩니다.

2021-09-19 01:42 UTC, wilco82 commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +    @Pattern(regexp = "^(?=.*[a-zA-Z0-9]).{6,12}$", message = "아이디는 영문/숫자 조합 6~12자리")
@

> 안녕하세요. 처음으로 다른 사람의 코드에 리뷰를 달아봅니다. 🙂
> 저와 코드를 진행하는 스타일이 다르지만, 나름 많은 걸 배웠습니다. 특히, 정규식은 어려워서 잘 사용안하려는 경향이 있었는데, 이 부분을 적극 활용하는 부분은 정말 인상 깊었습니다. 다만 패키지 구조에 대해서는 사전에 미리 토의를 하고 정한 틀이 있었는데, 그 부분을 반영하지 않으신 부분은 조금 당황스러웠습니다. ;; 세부 리뷰내용에도 이야기 했지만, 간단히 요약하자면,
> `com.project.doubleshop.domain.도메인이름.*`
> `com.project.doubleshop.web.도메인이름.*`
> 이런 식으로 진행하고자한게 기존에 구글밋으로 토의한 프로젝트 패키지의 큰 틀에 대한 내용 이었습니다. 아 그리고, f-lab에서 적극적으로 권장하는 사항 중 하나가 멘티끼리도 활발하게 리뷰를 하자는 항목이 있는 걸로 알고 있습니다. 리뷰어에서 멘토님만 등록하셨던 것 같은데, 저도 리뷰어로서 참여할 수 있게 해주셨으면 좋겠고, 제가 올린 pull request에도 적극적으로 리뷰를 해주시기 바랍니다. 감사합니다.

RE: 
안녕하세요 형중님 소중한 리뷰 감사합니다.
패키지 관련해서는 구글밋 토의 전에 패키지 네이밍만 먼저 했었는데, 이후에 구현하는 과정에서 깜빡 잊고 반영을 못했네요. 수정하겠습니다 :)

네, 저번에 말씀드렸다시피 저도 멘티 간에 피드백도 역시 필요하다는 점 동의합니다.
다만 리뷰어 등록에 대해서 해명을 해보자면, PR을 하면서 형중님과 멘토님을 같이 리뷰어로 지정하려 했는데, 오류가 생겼는지 이상하게 한 명 밖에 지정이 안 되더라구요.. 😅 이 부분은 제가 아직 깃허브 사용이 익숙하지 않아서 저의 실수였을 수도 있겠네요. 다음에 PR 할 때는 확실히 해보겠습니다. 감사합니다.

2021-09-19 02:09 UTC, wilco82 commented on src/main/java/com/project/doubleshop/controller/MemberController.java
> +package com.project.doubleshop.controller;
web.member 안에 controller 패키지도 따로 만드는 것은 어떨까요?

2021-09-19 04:16 UTC, wanniDev commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +    private MemberInfoMapper memberInfoMapper;
샘플 코드는 해당 프레임워크에 이해도를 높이기 위해, 기존의 객체지향에 맞는 구조를 포기하는 경우가 많습니다. 최악의 경우는 그냥 실행해보고, 잘 돌아가면 검토도 안하고 올리는 경우도 있고요. 이 부분은 전에 구글밋에서 키워드로 준 적이 있는데 그 부분을 다시 학습하시고, 살펴보면 좋을 것 같습니다. (`entity, repository, service, controller`)

2021-09-19 04:20 UTC, wanniDev commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +    @Pattern(regexp = "^(?=.*[a-zA-Z0-9]).{6,12}$", message = "아이디는 영문/숫자 조합 6~12자리")
@wilco82 제가 이 부분에 대해 의견을 드린 이유는 검증 로직이 DTO에 있을 필요가 있냐는 것이 었습니다. 백엔드 영역에서 검증을 할필요가 있냐고 물어본 건 아니었습니다.

2021-09-19 05:13 UTC, wanniDev commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +    @Pattern(regexp = "^(?=.*[a-zA-Z0-9]).{6,12}$", message = "아이디는 영문/숫자 조합 6~12자리")
@wilco82 아 그리고, 리뷰어 지정시 생기는 오류가 있다는 건 처음 알았네요. 혹시 어떤 오류였는지 정확하게 말씀해주실 수 있을까요? 검색해봐도 그런 종류의 오류는 없네요. 그리고 그런 일이 있었으면, 알려주셨으면 좋겠는데, 그냥 넘어가신게 조금 아쉽네요 😢

2021-09-20 00:42 UTC, wilco82 commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +    @Pattern(regexp = "^(?=.*[a-zA-Z0-9]).{6,12}$", message = "아이디는 영문/숫자 조합 6~12자리")
@wanniDev 네, 일단 유효성 검사는 저곳에서만 진행할 예정입니다.
리뷰어를 등록할 때 형중님을 먼저 지정하고 멘토님을 지정했는데 PR을 생성하고 나서 확인을 해보니 마지막에 지정한 멘토님만 등록이 되었습니다. 그래서 이후에 리뷰어 추가를 시도해봤는데 형중님 아이디가 검색만 되고 등록이 안 되더라구요.. 아마 제 실수이지 않았을까 싶은데, 다음에 요청 때도 같은 문제가 생기면 그때는 꼭 알려드리겠습니다.

2021-09-20 00:51 UTC, wilco82 commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +    private MemberInfoMapper memberInfoMapper;
네, 참고해보겠습니다.

2021-09-20 12:36 UTC, wanniDev commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +    @Pattern(regexp = "^(?=.*[a-zA-Z0-9]).{6,12}$", message = "아이디는 영문/숫자 조합 6~12자리")
유효성 검사에 대한 강우님의 입장은 잘 알겠지만, DTO에 담는 member의 데이터가 다른 종류에 DTO에 사용될 가능성이 큰만큼, 유효성 검사 관련 애노테이션은 member entity로 옮기시는게 더 확장성이 있어보이긴 합니다. 만약 강우님의 코드 구성대로라면, 다른 DTO에 member를 담을 때, 같은 유효성 검사 애노테이션을 copy&paste를 하게 될 것 같긴 하네요. 멘토님의 의견도 살펴보셔야 겠지만, 개인적인 소견은 DTO에 검증 로직을 넣는건 코드의 유연성이 떨어져 보입니다.

2021-09-21 00:47 UTC, f-lab-jason requested changes

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/exception/DuplicateEmailException.java
> +public class DuplicateEmailException extends IllegalArgumentException {
1. Custom error message를 추가해주시면 좋겠네요. `DuplicateIdException`두요
2. `Duplicated...`이 더 적절한 이름 같습니다.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/model/enums/Authority.java
> +    CONSUMER, SELLER, ADMIN;
nit: `enum`계열은 데이터를 한 줄 에 하나씩 표현해주는게 더 좋습니다. 늘어날 걸 대비해서요.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/SmsVerificationService.java
> +    public static final String SENDER_NUM = "+14405167177";
형중님께도 comment 드렸던 내용이긴한데 이런 데이터들은 Azure KeyVault같은 외부 저장소에 보관하고 코드에는 노출하지 않는게 원칙인데, 이건 내부 프로젝트이니 놔두도록 할게요.
지양해야할 부분이라는것만 기억해주시면 좋겠습니다 :)

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/SmsVerificationService.java
> +        String authMessage = "[Double Shop] 인증 번호 " + authNum + "를 입력하세요.";
`String.format()`을 써보는건 어떨까요?

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/SmsVerificationService.java
> +    }
1. 검증 후에 세션에 저장된 데이터는 삭제해주면 좋을 것 같아요.
2. 보통 코딩 컨벤션에서 public method들을 다 적어 준 다음에 private method들을 적어줍니다. 이부분은 private method 위로 옮겨주면 좋겠네요.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/SmsVerificationService.java
> +        session.setAttribute(phoneNum, authNum);
이 방식은 `session`의 생명주기와 auth token의 생명주기가 같은데..auth token의 경우는 보통 따로 유효기간(10분이라던지..)이 있을텐데 그 방법을 생각해보시면 좋겠네요.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +        }
중복검사 자체는 UI에서 사용할 중복체크용으로 필요하겠지만 `signUp`내부에서 이런 검사는 db table에 unique column을 설정할 경우 특별히 필요없을 것 같네요.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +        requestDto.passwordEncryption(encryptionUtil);
'행위'에 대한 메소드이니 `requestDto.encryptPassword()`가 더 나을 것 같네요.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/resources/mapper/memberMapper.xml
> +    </select>
이런 중복검사류의 쿼리는 만약 조회하는 colum에 index가 없다면 full scan을 해야할테니 top 1만 가져오는 부분을 추가해주시면 좋습니다.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/impl/MemberServiceImpl.java
> +        return memberInfoMapper.checkId(userId) == 1;
물론 그런 케이스는 없어야 겠지만, `>= 1` 혹은 `!= 0`이 더 안전한 체크라고 할 수 있겠네요.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/mapper/MemberInfoMapper.java
> +    int checkEmail(String email);
리턴값이 int이니 `checkXXX`보단 `getXXXCount`의 메소드명이 더 적절해보입니다.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/MemberService.java
> +    boolean checkEmailDuplicate(String email);
nit: 리턴형이 boolean인 경우는 보통 `isXXX` 혹은 `hasXXX`의 형태로 많이 씁니다.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/MemberService.java
> +    void signUp(MemberSaveRequestDto requestDto);
nit: `signUp`은 유저의 입장이고 서버입장에선 `registerUser`등이 조금 더 적절한 이름같아요.

2021-09-21 00:47 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/utils/SHA256EncryptionUtil.java
> +        String sha = "";
굳이 이 `sha`를 선언할 필요 없이 `StringBuilder`를 선언해주고 리턴해주면 좋을 것 같네요.

2021-09-21 02:31 UTC, wilco82 commented on src/main/java/com/project/doubleshop/dto/MemberSaveRequestDto.java
> +    public MemberSaveRequestDto(String userId, String password, String name, String email, String phone) {
이 부분은 제가 코드를 다듬는 과정에서 놓쳤던 것 같습니다. 수정하겠습니다.

2021-09-21 02:31 UTC, wilco82 commented on src/main/java/com/project/doubleshop/service/SmsVerificationService.java
> +    public static final String SENDER_NUM = "+14405167177";
네 감사합니다. 이 부분은 저도 한 번 말씀을 드리려고 했었는데요. 코드를 깃허브에 올리고 나서 몇 시간 뒤에 트윌리오 팀에서 메일이 왔는데, 발급받은 시드가 public하게 사용된 것을 감지해서 unauthorized access 방지 목적으로 기존의 데이터를 revoke하고 다시 새로운 토큰을 주더라구요. 그럼 멘토님께서 언급하신 것처럼 외부 저장소에 따로 보관을 하는 것이 좋을까요? 다른 인증 API에서도 자동 감지가 일어나는지는 모르겠습니다만, 사실 이 API를 선택한 가장 주된 이유가 sender의 번호를 무료로 만들어주었던 것이긴 합니다.

2021-09-21 05:25 UTC, f-lab-jason commented on src/main/java/com/project/doubleshop/service/SmsVerificationService.java
> +    public static final String SENDER_NUM = "+14405167177";
네 그럼 외부 secret 저장소를 쓰는 것이 좋겠네요. 형중님과 논의해서 같은 서비스를 사용하면 좋을 것 같습니다.

2021-09-23 07:45 UTC, wilco82 commented on src/main/java/com/project/doubleshop/utils/SHA256EncryptionUtil.java
> +        String sha = "";
그럼 24라인에서 toString() 메서드를 사용하지 않고 `password` 변수를 Stringbuilder 타입으로 선언해야 하나요?

2021-09-23 07:53 UTC, wilco82 commented on src/main/resources/mapper/memberMapper.xml
> +    </select>
감사합니다. 그럼 TOP 1만 가져오게 되면 resultType을 DTO 객체 타입으로 변경하고 `MemberInfoMapper`의 메서드도 수정해야 하나요? 제가 잘못 이해한 것 같아서 질문드렸습니다.

2021-09-24 15:57 UTC, wanniDev approved these changes

2021-09-25 04:21 UTC, merged